import { chromium } from 'playwright-core';
const EXE = process.env.HOME + '/Library/Caches/ms-playwright/chromium_headless_shell-1217/chrome-headless-shell-mac-arm64/chrome-headless-shell';
const OUT = new URL('.', import.meta.url).pathname;
const browser = await chromium.launch({ executablePath: EXE });
const page = await browser.newPage({ viewport: { width: 420, height: 760 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://localhost:8766/dao-vang/');
await page.waitForTimeout(300);
await page.click('[data-mode="classic"]');
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}rig-fixed-1.png`, clip: { x: 0, y: 0, width: 420, height: 320 } });
await page.waitForTimeout(400);
await page.screenshot({ path: `${OUT}rig-fixed-2.png`, clip: { x: 0, y: 0, width: 420, height: 320 } });
console.log('errors:', errors);
await browser.close();
